Models/ErrorViewModel.cs
namespace WebApplication2.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using WebApplication2.Models;
using System.Diagnostics;

namespace WebApplication2.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }
       

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/TinhLaiXuatController.cs
using Microsoft.AspNetCore.Mvc;

namespace WebApplication2.Controllers
{
    public class TinhLaiXuatController : Controller
    {
        public IActionResult TinhLaiXuat()
        {
            return View();
        }
        [HttpPost]
        
    public IActionResult TinhLaiXuat(int soTien, int kyHan, double laiSuat)
        {
            ViewData["soTien"] = soTien;
            ViewData["laiSuat"] = laiSuat;
            ViewData["kyHan"] = kyHan;
            ViewData["soTienLai"]= Math.Round(soTien * Math.Pow(1 + laiSuat / 100, kyHan)-soTien, 4);
            ViewData["tongSoTien"]= Math.Round(soTien*Math.Pow(1+laiSuat/100,kyHan),4);
           
            return View();
        }
        
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication2</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication2.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication2</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="TinhLaiXuat" asp-action="TinhLaiXuat">Tính Lãi Xuất</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication2 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/TinhLaiXuat/TinhLaiXuat.cshtml
@{
    ViewData["Title"] = "TinhLaiXuat";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="d-flex flex-column">
    <h1 class="text-center my-5 text-uppercase">công cụ tính lãi tiền gửi tiết kiệm</h1>
    <div class="col-12">
        <div class="d-flex flex-row justify-content-center gap-5">
            <div class="col-4 px-5 border rounded-3 d-flex flex-column justify-content-center shadow p-3 mb-5">
                <form action="/TinhLaiXuat/TinhLaiXuat" method="post">
                    <div class="mb-3">
                        <label for="soTien" class="form-label">Số tiền gửi</label>
                        <input type="text" class="form-control" id="soTien" name="soTien" value="@ViewData["SoTien"]" aria-describedby="text">
                    </div>
                    <div class="mb-3">
                        <label for="laiSuat" class="form-label">Lãi suất gửi (%)</label>
                        <input type="number" class="form-control" id="laiSuat" name="laiSuat" value="@ViewData["LaiSuat"]" aria-describedby="text">
                    </div>
                    <div class="mb-3">
                        <label for="kyHan" class="form-label">Kỳ hạn gửi</label>
                        <input type="number" class="form-control" id="kyHan" name="kyHan" value="@ViewData["KyHan"]" aria-describedby="text">
                    </div>
                    <div class="d-flex align-items-center justify-content-center mt-5">
                        <button type="submit" id="ketqua" class="btn btn-primary px-4 py-2">Xem kết quả</button>
                    </div>
                </form>
            </div>
            <div class="col-4 px-5 border rounded-3 d-flex flex-column justify-content-center shadow p-3 mb-5">
                <div class="mb-5">
                    <label for="soTienLai" class="form-label fw-bold">Số tiền lãi nhận được</label>
                    <input type="text" class="form-control" id="soTienLai" name="soTienLai" value="@ViewData["SoTienLai"]" aria-describedby="text">
                </div>
                <div class="mb-3">
                    <label for="tongSoTien" class="form-label fw-bold">Tổng số tiền nhận được khi đến hạn</label>
                    <input type="text" class="form-control" id="tongSoTien" name="tongSoTien" value="@ViewData["TongSoTien"]" aria-describedby="text">
                </div>
            </div>
        </div>
    </div>
</div>